config/routes.rb
Shakespeare::Application.routes.draw do
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => 'drama#index'

  get "drama/index"

  resources :performances
  resources :lines
  resources :scenes
  resources :users
  resources :sessions

  match 'drama/create_performance' => 'drama#create_performance'

end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :scene
  has_many :performances, dependent: :destroy
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  before_filter :require_login

  layout "admin"

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lines }
    end
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
    @line = Line.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line }
    end
  end

  # GET /lines/new
  # GET /lines/new.json
  def new
    @line = Line.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line }
    end
  end

  # GET /lines/1/edit
  def edit
    @line = Line.find(params[:id])
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(params[:line])

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render json: @line, status: :created, location: @line }
      else
        format.html { render action: "new" }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lines/1
  # PUT /lines/1.json
  def update
    @line = Line.find(params[:id])

    respond_to do |format|
      if @line.update_attributes(params[:line])
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line = Line.find(params[:id])
    @line.destroy

    respond_to do |format|
      format.html { redirect_to lines_url }
      format.json { head :ok }
    end
  end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
  <% if @line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% @line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :character %><br />
    <%= f.text_field :character %>
  </div>
  <div class="field">
    <%= f.label :line %><br />
    <%= f.text_area :line %>
  </div>
  <div class="field">
    <%= f.label :line_order %><br />
    <%= f.number_field :line_order %>
  </div>
  <div class="field">
    <%= f.label :scene_id %><br />
    <%= f.number_field :scene_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>Editing line</h1>

<%= render 'form' %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<h1>Listing lines</h1>

<table>
  <tr>
    <th>Character</th>
    <th>Line</th>
    <th>Line order</th>
    <th>Scene</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lines.each do |line| %>
  <tr>
    <td><%= line.character %></td>
    <td><%= line.line %></td>
    <td><%= line.line_order %></td>
    <td><%= line.scene_id %></td>
    <td><%= link_to 'Show', line %></td>
    <td><%= link_to 'Edit', edit_line_path(line) %></td>
    <td><%= link_to 'Destroy', line, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line', new_line_path %>

app/views/lines/new.html.erb
<h1>New line</h1>

<%= render 'form' %>

<%= link_to 'Back', lines_path %>

app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Character:</b>
  <%= @line.character %>
</p>

<p>
  <b>Line:</b>
  <%= @line.line %>
</p>

<p>
  <b>Line order:</b>
  <%= @line.line_order %>
</p>

<p>
  <b>Scene:</b>
  <%= @line.scene_id %>
</p>


<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>