config/routes.rb
Shakespeare::Application.routes.draw do
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => 'drama#index'

  get "drama/index"

  resources :performances
  resources :lines
  resources :scenes
  resources :users
  resources :sessions

  match 'drama/create_performance' => 'drama#create_performance'

end

app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :line , :counter_cache => true 
  # see http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html
  
  validates :video_url, presence: true, :format => URI::regexp(%w(http https))
  
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  
  before_filter :require_login

  layout "admin"
  
  # GET /performances
  # GET /performances.json
  def index
    @performances = Performance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @performances }
    end
  end

  # GET /performances/1
  # GET /performances/1.json
  def show
    @performance = Performance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @performance }
    end
  end

  # GET /performances/new
  # GET /performances/new.json
  def new
    @performance = Performance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @performance }
    end
  end

  # GET /performances/1/edit
  def edit
    @performance = Performance.find(params[:id])
  end

  # POST /performances
  # POST /performances.json
  def create
    @performance = Performance.new(params[:performance])

    respond_to do |format|
      if @performance.save
        format.html { redirect_to @performance, notice: 'Performance was successfully created.' }
        format.json { render json: @performance, status: :created, location: @performance }
      else
        format.html { render action: "new" }
        format.json { render json: @performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /performances/1
  # PUT /performances/1.json
  def update
    @performance = Performance.find(params[:id])

    respond_to do |format|
      if @performance.update_attributes(params[:performance])
        format.html { redirect_to @performance, notice: 'Performance was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performances/1
  # DELETE /performances/1.json
  def destroy
    @performance = Performance.find(params[:id])
    @performance.destroy

    respond_to do |format|
      format.html { redirect_to performances_url }
      format.json { head :ok }
    end
  end
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/performances/_form.html.erb
<%= form_for(@performance) do |f| %>
  <% if @performance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@performance.errors.count, "error") %> prohibited this performance from being saved:</h2>

      <ul>
      <% @performance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line_id %><br />
    <%= f.number_field :line_id %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br />
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br />
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :twitter_name %><br />
    <%= f.text_field :twitter_name %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/performances/edit.html.erb
<h1>Editing performance</h1>

<%= render 'form' %>

<%= link_to 'Show', @performance %> |
<%= link_to 'Back', performances_path %>

app/views/performances/index.html.erb
<h1>Listing performances</h1>

<table>
  <tr>
    <th>Line</th>
    <th>Video url</th>
    <th>Email address</th>
    <th>Twitter name</th>
    <th>Approved?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @performances.each do |performance| %>
  <tr>
    <td><%= performance.line_id %></td>
    <td><%= performance.video_url %></td>
    <td><%= performance.email_address %></td>
    <td><%= performance.twitter_name %></td>
    <td><%= performance.approved %></td>
    <td><%= link_to 'Show', performance %></td>
    <td><%= link_to 'Edit', edit_performance_path(performance) %></td>
    <td><%= link_to 'Destroy', performance, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Performance', new_performance_path %>

app/views/performances/new.html.erb
<h1>New performance</h1>

<%= render 'form' %>

<%= link_to 'Back', performances_path %>

app/views/performances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Line:</b>
  <%= @performance.line_id %>
</p>

<p>
  <b>Video url:</b>
  <%= @performance.video_url %>
</p>

<p>
  <b>Email address:</b>
  <%= @performance.email_address %>
</p>

<p>
  <b>Twitter name:</b>
  <%= @performance.twitter_name %>
</p>

<p>
  <b>Approved:</b>
  <%= @performance.approved %>
</p>


<%= link_to 'Edit', edit_performance_path(@performance) %> |
<%= link_to 'Back', performances_path %>